# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 560)
        MainWindow.setMinimumSize(QtCore.QSize(445, 560))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(18, 120, 401, 151))
        self.groupBox.setObjectName("groupBox")
        self.dictApp = QtWidgets.QLineEdit(self.groupBox)
        self.dictApp.setGeometry(QtCore.QRect(10, 50, 301, 21))
        self.dictApp.setText("")
        self.dictApp.setObjectName("dictApp")
        self.btnBuscarApp = QtWidgets.QPushButton(self.groupBox)
        self.btnBuscarApp.setGeometry(QtCore.QRect(320, 50, 71, 21))
        self.btnBuscarApp.setObjectName("btnBuscarApp")
        self.labelDirApp = QtWidgets.QLabel(self.groupBox)
        self.labelDirApp.setGeometry(QtCore.QRect(10, 30, 211, 21))
        self.labelDirApp.setObjectName("labelDirApp")
        self.btnBuscarVenv = QtWidgets.QPushButton(self.groupBox)
        self.btnBuscarVenv.setGeometry(QtCore.QRect(320, 110, 71, 21))
        self.btnBuscarVenv.setObjectName("btnBuscarVenv")
        self.dictVenv = QtWidgets.QLineEdit(self.groupBox)
        self.dictVenv.setGeometry(QtCore.QRect(10, 110, 301, 21))
        self.dictVenv.setObjectName("dictVenv")
        self.labelDirVenv = QtWidgets.QLabel(self.groupBox)
        self.labelDirVenv.setGeometry(QtCore.QRect(10, 90, 211, 21))
        self.labelDirVenv.setObjectName("labelDirVenv")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(18, 280, 401, 151))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnTestar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnTestar.setGeometry(QtCore.QRect(320, 49, 71, 21))
        self.btnTestar.setObjectName("btnTestar")
        self.serverName = QtWidgets.QLineEdit(self.groupBox_2)
        self.serverName.setGeometry(QtCore.QRect(10, 49, 211, 21))
        self.serverName.setObjectName("serverName")
        self.labelServerName = QtWidgets.QLabel(self.groupBox_2)
        self.labelServerName.setGeometry(QtCore.QRect(10, 29, 211, 21))
        self.labelServerName.setObjectName("labelServerName")
        self.port = QtWidgets.QSpinBox(self.groupBox_2)
        self.port.setGeometry(QtCore.QRect(230, 49, 81, 21))
        self.port.setMinimum(0)
        self.port.setMaximum(65000)
        self.port.setObjectName("port")
        self.labelPorta = QtWidgets.QLabel(self.groupBox_2)
        self.labelPorta.setGeometry(QtCore.QRect(230, 30, 101, 21))
        self.labelPorta.setObjectName("labelPorta")
        self.progressTestBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressTestBar.setGeometry(QtCore.QRect(10, 90, 381, 21))
        self.progressTestBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressTestBar.setProperty("value", 0)
        self.progressTestBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressTestBar.setInvertedAppearance(False)
        self.progressTestBar.setObjectName("progressTestBar")
        self.status = QtWidgets.QLabel(self.groupBox_2)
        self.status.setGeometry(QtCore.QRect(10, 115, 71, 31))
        self.status.setObjectName("status")
        self.labelStatusServer = QtWidgets.QLabel(self.groupBox_2)
        self.labelStatusServer.setGeometry(QtCore.QRect(70, 120, 151, 21))
        self.labelStatusServer.setText("")
        self.labelStatusServer.setObjectName("labelStatusServer")
        self.labelStatusPorta = QtWidgets.QLabel(self.groupBox_2)
        self.labelStatusPorta.setGeometry(QtCore.QRect(230, 120, 161, 21))
        self.labelStatusPorta.setText("")
        self.labelStatusPorta.setObjectName("labelStatusPorta")
        self.separador = QtWidgets.QLabel(self.groupBox_2)
        self.separador.setGeometry(QtCore.QRect(216, 110, 21, 41))
        self.separador.setText("")
        self.separador.setObjectName("separador")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(18, 10, 401, 91))
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setObjectName("logo")
        self.labelLink = QtWidgets.QLabel(self.centralwidget)
        self.labelLink.setGeometry(QtCore.QRect(18, 490, 121, 41))
        self.labelLink.setOpenExternalLinks(True)
        self.labelLink.setObjectName("labelLink")
        self.endServer = QtWidgets.QPushButton(self.centralwidget)
        self.endServer.setGeometry(QtCore.QRect(338, 450, 81, 23))
        self.endServer.setObjectName("endServer")
        self.startServer = QtWidgets.QPushButton(self.centralwidget)
        self.startServer.setGeometry(QtCore.QRect(250, 450, 82, 23))
        self.startServer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.startServer.setObjectName("startServer")
        self.linkWI2L = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.linkWI2L.setGeometry(QtCore.QRect(140, 490, 280, 40))
        self.linkWI2L.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.linkWI2L.setObjectName("linkWI2L")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.dictApp, self.btnBuscarApp)
        MainWindow.setTabOrder(self.btnBuscarApp, self.dictVenv)
        MainWindow.setTabOrder(self.dictVenv, self.btnBuscarVenv)
        MainWindow.setTabOrder(self.btnBuscarVenv, self.serverName)
        MainWindow.setTabOrder(self.serverName, self.port)
        MainWindow.setTabOrder(self.port, self.btnTestar)
        MainWindow.setTabOrder(self.btnTestar, self.startServer)
        MainWindow.setTabOrder(self.startServer, self.endServer)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Start Server Django"))
        self.groupBox.setTitle(_translate("MainWindow", "DIRETÓRIOS"))
        self.btnBuscarApp.setText(_translate("MainWindow", "BUSCAR..."))
        self.labelDirApp.setText(_translate("MainWindow", "<b>DIRETÓRIO DA APLICAÇÃO</b>"))
        self.btnBuscarVenv.setText(_translate("MainWindow", "BUSCAR..."))
        self.labelDirVenv.setText(_translate("MainWindow", "<b>DIRETÓRIO DA VirutalEnv (venv)</b>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "INFORMAÇÕES DO SERVIDOR"))
        self.btnTestar.setText(_translate("MainWindow", "TESTAR"))
        self.labelServerName.setText(_translate("MainWindow", "<b>NOME DO SERVIDOR<b>"))
        self.labelPorta.setText(_translate("MainWindow", "<b>PORTA<b>"))
        self.status.setText(_translate("MainWindow", "<b style=\"font-size: 11pt;\">Status:<b>"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body>\n"
"<div align=\"center\"><img src=\"../images/Logo_StartServerDjango.png\"/></div>\n"
"</body></html>"))
        self.labelLink.setText(_translate("MainWindow", "<b style=\" font-size:10pt;\">Desenvolvido por: </b>"))
        self.endServer.setText(_translate("MainWindow", "PARAR"))
        self.startServer.setText(_translate("MainWindow", "INICIAR"))
        self.linkWI2L.setText(_translate("MainWindow", "Willamy Domingos - WI2L"))

